---
apiVersion: v1
kind: Service
metadata:
  name: meshcentral-keda-http-interceptor
  namespace: extras
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local.
  ports:
    - name: http
      port: 8443
---
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: meshcentral-scaler
spec:
  hosts:
    - mesh.brhd.io
  scaleTargetRef:
    name: meshcentral
    kind: Deployment
    apiVersion: apps/v1
    service: meshcentral
    port: 8443
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800 # 30 minutes
  scalingMetric:
    concurrency:
      targetValue: 1
