---
apiVersion: v1
kind: Service
metadata:
  name: code-server-keda-http-interceptor
  namespace: extras
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local.
  ports:
    - name: http
      port: 8080
---
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: code-server-scaler
spec:
  hosts:
    - vs.brhd.io
  scaleTargetRef:
    name: code-server
    kind: Deployment
    apiVersion: apps/v1
    service: code-server
    port: 8080
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800 # 30 minutes
  scalingMetric:
    concurrency:
      targetValue: 1
