---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ignis-vaults
  namespace: privacy
  labels:
    app.kubernetes.io/name: ignis
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs-subdir
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ignis-app
  namespace: privacy
  labels:
    app.kubernetes.io/name: ignis
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs-subdir
  resources:
    requests:
      storage: 2Gi
