apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  destination:
    name: ''
    namespace: keda
    name: in-cluster
  source:
    path: kubernetes/cluster/extras/keda
    repoURL: 'https://github.com/maxim-mityutko/home-infra.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
