apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - dns-endpoint.yaml
  - scaler.yaml
helmCharts:
  - name: victoria-metrics-mcp
    namespace: ai
    releaseName: vm-mcp
    version: 0.3.0
    repo: https://victoriametrics.github.io/helm-charts/
    valuesInline:
      fullnameOverride: vm-mcp
      env:
        - name: MCP_LOG_LEVEL
          value: warn
      vm:
        type: single
        entrypoint: http://vmsingle-stack.monitoring.svc.cluster.local.:8428
      mcp:
        mode: http
        disable:
          tools: []
          resources: false
      service:
        type: ClusterIP
        port: 8080
      serviceAccount:
        create: true
        automount: false
      securityContext:
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
      resources:
        requests:
          cpu: 75m
          memory: 500Mi
        limits:
          memory: 750Mi
      ingress:
        enabled: true
        # TODO: tighten the security for the MCP server
        annotations:
          kubernetes.io/ingress.class: public
          cert-manager.io/cluster-issuer: lets-encrypt
        hosts:
          - host: mcp.vm.brhd.io
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: mcp-vm-brhd-io-tls
            hosts:
              - mcp.vm.brhd.io
      route:
        enabled: false
      livenessProbe:
        initialDelaySeconds: 10
        timeoutSeconds: 5
        periodSeconds: 30
      readinessProbe:
        initialDelaySeconds: 10
        timeoutSeconds: 5
        periodSeconds: 30
      scrape:
        enabled: false
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/revisionHistoryLimit
        value: 1
  - target:
      group: networking.k8s.io
      kind: Ingress
      name: vm-mcp
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: keda-http-interceptor
