apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dns-endpoint.yaml
  - secret.yaml
helmCharts:
  - name: vikunja
    namespace: privacy
    releaseName: vikunja
    version: v2.0.2
    repo: oci://ghcr.io/go-vikunja/helm-chart
    valuesFile: values.yaml
patches:
  - target:
      kind: Deployment
      name: vikunja
    # patch: |-
    #   - op: replace
    #     path: /spec/template/spec/containers/0/livenessProbe
    #     value:
    #       tcpSocket:
    #         port: http
    #       initialDelaySeconds: 30
    #       periodSeconds: 30
    #       timeoutSeconds: 3
    #       failureThreshold: 3
