apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  destination:
    name: in-cluster
    namespace: kube-dashboard
  source:
    path: kubernetes/cluster/default/headlamp
    repoURL: 'https://github.com/maxim-mityutko/home-infra.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
