apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/instance: victoria-metrics
  name: argocd-metrics
  namespace: argocd
spec:
  endpoints:
    - port: metrics
      interval: 300s
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchExpressions:
      - key: app.kubernetes.io/part-of
        operator: In
        values:
          - argocd
      - key: app.kubernetes.io/name
        operator: In
        values:
          - argocd-applicationset-controller
          - argocd-dex-server
          - argocd-metrics
          - argocd-notifications-controller-metrics
          - argocd-repo-server
          - argocd-server-metrics
