---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: browserless
  namespace: ai
spec:
  encryptedData:
    TOKEN: AgC7Bos1xBQuJJozTXINXY4cDyQHiZcDUFea9w//CzELhW6aGjAZgOkTjhHTRJNidJvBEVSgwgBy+cFDFlGn7kBN8VQPcZi66tiZ80tjccsTQRNtqSy5oH0VmNct6gm3G50X+/uYUlKJNBBxKhoujVn4MtdKKHVYIgmcWSUCZJJCNcvV7k0IfRkPU9RU8mny2jCcPG36sZnSMcC3/KPnCuIWG3E0ApjN5i8bVL1nkBD8AqqcC9a6kaQrrmhIvmB1ADqFOiqDPzVGnrVwa7oJ0N+rTdl73qnYrkpdmTwM2Rw7I5UjQK7vqnDxB9vwjJYk4vYaWzcmLDkmN+Duq4/UVbgU/ix4qXaSiUIZ0SMvHUshGnT+afA6S8apbvA6gYtmWj/eHn4OIuOJ7ba/fJhnQ7eGXlCV1qOFIGxu08Ori+KXyKCV632KF29mXdNlj7id2C1RlgDa6pHzoBszN7ai2csxybMVoigJjhNAmDXryXaYXwbIdulCHYkwE4m6nB4SSre7Ijruksl5hFXSXvhJ9wRJ6e9fw8yvTuPmX9W6IV0Uhqc1tarK25eya41dtw5ADoItlUj+PxFlLvRNH1WdBd7DY4oB6S1xN8elZhhWG0Z3aKchlG2r/JFhbGXFWC9LGr8lKlvbrWiWvcFtwMCOaxc5mRXQcFwPXGgbLo8soAxPmC/132dvMwwu6zwYKyMCFmRQsj1DNRhcSRoMwTVP9p5Zx+R7ftkeAGkahY8Z
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: browserless
      name: browserless
      namespace: ai
    type: Opaque
