kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: bento-pdf-scaling
spec:
  hosts:
    - pdf.brhd.io
  scaleTargetRef:
    name: bento-pdf
    kind: Deployment
    apiVersion: apps/v1
    service: bento-pdf
    port: 8080
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
  scalingMetric: # requestRate and concurrency are mutually exclusive
    requestRate:
      granularity: 1s
      targetValue: 1
      window: 1m0s
