---
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: bento-pdf-scaler
spec:
  target:
    service: bento-pdf
    port: 8080
  rules:
    - hosts:
        - pdf.brhd.io
  scalingMetric:
    concurrency:
      targetValue: 50
  # timeouts:
  #   readiness: 30s
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bento-pdf-scaler
spec:
  scaleTargetRef:
    name: bento-pdf
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 60
  initialCooldownPeriod: 600 
  cooldownPeriod: 1800
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: bento-pdf-scaler
