# ================================================================================================
# Daily restart of the Calico DaemonSet
# ================================================================================================
apiVersion: batch/v1
kind: CronJob
metadata:
  name: calico-node-restart
  namespace: kube-system
spec:
  schedule: "5 7 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: calico-node
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -e
            - /scripts/restart-calico-node.sh
            volumeMounts:
            - name: calico-scripts
              mountPath: /scripts
              readOnly: true
          volumes:
          - name: calico-scripts
            configMap:
              name: calico-scripts
          restartPolicy: Never
