---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keeper-data
  namespace: privacy
  labels:
    app.kubernetes.io/name: keeper
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-subdir
  resources:
    requests:
      storage: 5Gi
