apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gpu
resources:
  - service-scrape.yaml
helmCharts:
  - name: drm-exporter
    namespace: gpu
    releaseName: drm-exporter
    version: 0.2.5
    repo: oci://ghcr.io/home-operations/charts
    valuesInline:
      fullnameOverride: drm-exporter
      monitoring:
        dashboards:
          enabled: true
          labels:
            grafana-dashboard: "true"
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
      resources:
        limits:
          gpu.intel.com/i915_monitoring: 1
        requests:
          gpu.intel.com/i915_monitoring: 1
