---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openclaw
  namespace: openclaw
  labels:
    app.kubernetes.io/name: openclaw
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  rules:
    - host: openclaw.brhd.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: openclaw
                port:
                  name: gateway
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: openclaw.brhd.io
  namespace: openclaw
spec:
  endpoints:
    - dnsName: openclaw.brhd.io
      recordTTL: 86400
      recordType: CNAME
      targets:
        - casa.brhd.io
