apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw
resources:
  - volumes.yaml
  - openclaw.yaml
  - secret.yaml
  - ingress.yaml
configMapGenerator:
  - name: openclaw-config
    files:
    - config/config.yml
