apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw
resources:
  - volumes.yaml
  - openclaw.yaml
  - secret.yaml
  - ingress.yaml
configMapGenerator:
  - name: openclaw-config
    files:
      - openclaw.json=config/openclaw.json
      - AGENTS.md=config/AGENTS.md
  - name: rbw-config
    files:
      - rbw.json=config/rbw.json
