---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openclaw
  namespace: openclaw
spec:
  encryptedData:
    OLLAMA_API_KEY: AgAkncN2McfEJzhesh1KVmKAlpHV+driPK60rIkXjWUCkE6/u8wh3lR/x94X4fhYUuJ1rDtgwPRtEwGo/FYDPwhOAjUanWfcgb7JGXsKh9lcsL4Zb0A7aiW7uBFX1aPxWoeJV27ZSC8IaVK2oRKe2sn0a7pVGahQ5XKdjT0zCAfTfWrlhnWt8ydlpDLUaQqvL+7fZ4vfXdLz+8Gca53QbNd49WIOTHs/UHPrE0qDWWDhJUO5zfF7sHqjCNDzu5zRcGbNwEgEOSJ0KoiPjOelpaxUV+UsZvRczg8UPPiAWge6016XdJ1RT0O2xSNY5XR601GthGKcwRG/mQUsN65XVr503C4KQwItyEHZ8gf13dKoQZ+lnXgnH3jxKvOplvGmgM2nFGQ1nX6aqRH6bTORbyW+BKsgLpRVnvTPoOM4KMZvyTRVPTxOuA0TUxoOEnRrlERj+46McdLnPOwNcJcYfNB0ZFaemty9lfJpIK6ZxCg9HfdqMllkI2+8THZdKf5wnItJJWM16TQOe8//PaCmSqy5l63jca8OQk0iY6vLrUAMcpueRB7XOHLgOaH6qANdVuHh4ldlATEflUxOqEOtS47VOeZr2QggQMO8iwfaDDlycNn1aTuEzjFw6XaOHhP04le5SwR0wHfYwjL04Rt6cNZiLO0NBriZDeWHtxG5xSfpygZalpGo6gXNOlL/IqmhSjFanth8S160Rui+qtSIfgMZBKG/5pgnwY094BZx2i+TqlU7b4tvX7z3VQdOn4NboX54U8W6HLhrK0I=
    OPENCLAW_GATEWAY_TOKEN: AgBu0zqU0AGW9oL5z7MosWA4ofExIxt/2bNAQ1FlLdxH89qmrr6M7ccyNaMt6xoF8C6tB3BjE/laZn9Hz7SV033rqeNQ+VmB4o4TJKhlIEMhpJNExW/JVcBVknteDnKBLrq0qEJuONKMqsvmY/MM6CaX4hsrvtXNvsX/bMiZlvzGtI7Hkw8brDgw99gvQYgfl1PQK5X1y3sibCoRNvjnbhKvQdOKOwxMiuQ4rk55LTvfyEXwz8HgeTTPoPil5/EMaW66U3fl/D/ebKi6bkisaTPgGnJFQCfJjt6wMp/rKj468RP6KbztiayCt73FjzeD1/frcC1Z2lpDmfgn5Fi8cFUiMETl8KiP9LHOdjjR2RQW4D20OvSP81bI44Czi2uAdBBUOGfbqwelDZWaqi3FcjW0bNXJwxGY+NmX1uIBQ1IvwunWIxb5gCWr9n2uRqWxFq+5Z/6JDLjLAkcbuBAjdjBlImciBMFMDNdMwDzrAVKhbZuQP8rsC5wHgm9CSYuYsKWHFkhPrbOzFgB5LgDFGfawSy5bDA5FDWfO8XwzZ9O325ylixRqdsza3Q68nOF7SU+0YQFNvfgR9AwGNsTbuV0Ih4HBYsHPw0p5sl+SyOQfyVA68IO45vi7tkM7QzY7F8T8KtUhCk2uamNCWKGTj5694CZ11v4GDZRB1d9oeHXDH+rBOepoiVROIAg2YFL/dl0xRyMrQVEorMK8ewECq/tL+BwIboNE3gwa7Uuw
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: openclaw
      name: openclaw
      namespace: openclaw
    type: Opaque