---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openclaw
  namespace: openclaw
spec:
  encryptedData:
    OLLAMA_API_KEY: AgAkncN2McfEJzhesh1KVmKAlpHV+driPK60rIkXjWUCkE6/u8wh3lR/x94X4fhYUuJ1rDtgwPRtEwGo/FYDPwhOAjUanWfcgb7JGXsKh9lcsL4Zb0A7aiW7uBFX1aPxWoeJV27ZSC8IaVK2oRKe2sn0a7pVGahQ5XKdjT0zCAfTfWrlhnWt8ydlpDLUaQqvL+7fZ4vfXdLz+8Gca53QbNd49WIOTHs/UHPrE0qDWWDhJUO5zfF7sHqjCNDzu5zRcGbNwEgEOSJ0KoiPjOelpaxUV+UsZvRczg8UPPiAWge6016XdJ1RT0O2xSNY5XR601GthGKcwRG/mQUsN65XVr503C4KQwItyEHZ8gf13dKoQZ+lnXgnH3jxKvOplvGmgM2nFGQ1nX6aqRH6bTORbyW+BKsgLpRVnvTPoOM4KMZvyTRVPTxOuA0TUxoOEnRrlERj+46McdLnPOwNcJcYfNB0ZFaemty9lfJpIK6ZxCg9HfdqMllkI2+8THZdKf5wnItJJWM16TQOe8//PaCmSqy5l63jca8OQk0iY6vLrUAMcpueRB7XOHLgOaH6qANdVuHh4ldlATEflUxOqEOtS47VOeZr2QggQMO8iwfaDDlycNn1aTuEzjFw6XaOHhP04le5SwR0wHfYwjL04Rt6cNZiLO0NBriZDeWHtxG5xSfpygZalpGo6gXNOlL/IqmhSjFanth8S160Rui+qtSIfgMZBKG/5pgnwY094BZx2i+TqlU7b4tvX7z3VQdOn4NboX54U8W6HLhrK0I=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: openclaw
      name: openclaw
      namespace: openclaw
    type: Opaque