apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-data
  namespace: openclaw
  labels:
    app.kubernetes.io/name: openclaw
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: nfs-subdir
  resources:
    requests:
      storage: 10G
