---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openclaw-data-iscsi
  namespace: ai
  labels:
    app.kubernetes.io/name: openclaw
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      storage.target: openclaw-data-iscsi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openclaw-data-iscsi
  namespace: ai
  labels:
    app.kubernetes.io/name: openclaw
    storage.target: openclaw-data-iscsi
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 20Gi
  iscsi:
    targetPortal: 192.168.12.10
    iqn: iqn.2005-10.org.freenas.ctl:k8s.openclaw
    lun: 0
    fsType: ext4
    readOnly: false
