apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-vectorchord
# Ref: https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5-0.3.0
  imagePullPolicy: IfNotPresent
  instances: 1
  enablePDB: false
  primaryUpdateStrategy: unsupervised
  logLevel: info

  postgresql:
    # Ref: https://github.com/tensorchord/cloudnative-pgvecto.rs
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      timezone: "Etc/UTC"
      max_slot_wal_keep_size: 200MB
      archive_timeout: 60min

  managed:
    # Ref: https://cloudnative-pg.io/documentation/current/service_management/
    services:
      disabledDefaultServices: ["r","ro"]

  enableSuperuserAccess: true
  superuserSecret:
    name: cnpg-default-secret
  
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
    limits:
      memory: 1Gi
  
  storage:
    size: 5Gi
    # resizeInUseVolumes: true
    storageClass: nfs-subdir

  # Ref: https://cloudnative-pg.io/documentation/current/wal_archiving/#plugin-based-architecture
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      # Ref: https://github.com/cloudnative-pg/plugin-barman-cloud/issues/682
      isWALArchiver: true
      parameters:
        serverName: cnpg-vectorchord
        barmanObjectName: cnpg-vectorchord-barman

  # Ref: https://cloudnative-pg.io/documentation/current/instance_manager/
  startDelay: 120
  stopDelay: 30
  smartShutdownTimeout: 15
  probes:
    readiness:
      initialDelaySeconds: 15
      timeoutSeconds: 5
      periodSeconds: 30
    liveness:
      initialDelaySeconds: 15
      timeoutSeconds: 5
      periodSeconds: 30

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: feature.node.kubernetes.io/storage-nonrotationaldisk
              operator: In
              values: ["true"]
  bootstrap:
    # Ref: https://cloudnative-pg.io/documentation/current/recovery/#recovery-from-a-backup-object
    recovery:
      source: cnpg-vectorchord-backup
      # recoveryTarget:
      #   targetTime: "2025-01-01 00:00:00.00000+00"  # PITR

  externalClusters:
    - name: cnpg-vectorchord-backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: cnpg-vectorchord-barman
          serverName: cnpg-vectorchord

  # NOTE: keeping `bootstrap` section here for reference, refer to
  # CloudNativePG documentation for more details.
  # Ref: https://cloudnative-pg.io/documentation/current/bootstrap/
  # Ref: https://cloudnative-pg.io/documentation/current/database_import/
  # bootstrap:
  #   initdb:
  #     import:
  #       type: monolith
  #       databases:
  #         - immich
  #       roles:
  #         - immich
  #       source:
  #         externalCluster: cnpg-pgvectors
  # externalClusters:
  #   - name: cnpg-pgvectors
  #     connectionParameters: 
  #       host: cnpg-pgvectors-rw.default.svc
  #       dbname: postgres
  #       user: postgres
  #     password:
  #       name: cnpg-default-secret
  #       key: password
