---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-omada-customdns
  namespace: default
  labels:
    app.kubernetes.io/name: blocky
    app.kubernetes.io/component: omada-sync
data:
  omada-custom-dns.yml: |
    customDNS:
      filterUnmappedTypes: true
      zone: |
        $ORIGIN internal.brhd.io.
        $TTL 3600
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-omada-clientlookup
  namespace: default
  labels:
    app.kubernetes.io/name: blocky
    app.kubernetes.io/component: omada-sync
data:
  omada-client-lookup.yml: |
    clientLookup:
      upstream: 192.168.12.1
      clients: {}
