# Ref: https://filebrowserquantum.com/en/docs/getting-started/v2/migration/
# Ref: https://filebrowserquantum.com/en/docs/reference/full-config-example/
server:
  database:
    path: data/filebrowser.sqlite
    migrateFrom: data/database.db.old
  numImageProcessors: 2
  disablePreviews: false
  disablePreviewResize: false
  disableTypeDetectionByHeader: false
  logging:
    - levels: "info|warning|error"
      apiLevels: "warning|error"
      output: stdout
      noColors: false
      utc: true
  sources:
    - path: /home/filebrowser/data/sources/drive/shared
      name: Shared
      config:
        rules:
          - folderPath: /
            ignoreHidden: true
            ignoreZeroSizeFolders: false
          - fileName: ".DS_Store"
        defaultUserScope: /
        defaultEnabled: true
        createUserDir: false
        defaultPermissions:
          view: true
          download: true
          modify: true
          delete: true
          create: true
          configured: true
    - path: /home/filebrowser/data/sources/drive/users
      name: DeGoogle
      config:
        rules:
          - folderPath: /
            ignoreHidden: true
            ignoreZeroSizeFolders: false
          - fileName: ".DS_Store"
        defaultUserScope: /
        defaultEnabled: true
        createUserDir: true
        defaultPermissions:
          view: true
          download: true
          modify: true
          delete: true
          create: true
          configured: true
  cacheDir: tmp
  maxArchiveSize: 1 # in GB
http:
  port: 8080
  baseURL: /
  externalUrl: https://drive.brhd.io
  internalUrl: ""
  trustProxyHeaders: true
  disableWebDAV: false
auth:
  tokenExpirationHours: 2
  methods:
    proxy:
      enabled: false
    noauth: false
    password:
      enabled: false
      signup: false
    # Ref: https://github.com/gtsteffaniak/filebrowser/wiki/Configuration-And-Examples#openid-connect-configuration-oidc
    oidc:
      enabled: true
      issuerUrl: "https://auth.brhd.io/application/o/filebrowser/"
      scopes: "email openid profile x_groups"
      userIdentifier: "email"
      disableVerifyTLS: false
      logoutRedirectUrl: "https://auth.brhd.io/application/o/filebrowser/end-session/"
      adminGroup: admin
      userGroups:
        - admin
        - user
      groupsClaim: groups
  adminUsername: admin
frontend:
  name: Filebrowser Quantum
  disableDefaultLinks: false
  disableUsedPercentage: false
userDefaults:
  sidebar:
    sticky: true
  listing:
    viewMode: normal
    singleClick: true
    showHidden: false
    dateFormat: false
    gallerySize: 3
    quickDownload: true
  preview:
    highQuality: false
    image: false
    video: false
    audio: false
    motionVideoPreview: false
    office: false
    popup: false
    folder: false
    models: false
    disablePreviewExt: ""
  fileViewer:
    autoplayMedia: false
    disableOnlyOfficeExt: .txt .csv .html .pdf
  ui:
    darkMode: true
    locale: en
    themeColor: var(--blue)
  account:
    permissions:
      api: false
      admin: false
      share: true
      realtime: false
    lockPassword: true
    disableSettings: false
    loginMethod: oidc
    disableUpdateNotifications: true
integrations:
  media:
    ffmpegPath: /usr/local/bin
    debug: false
    
