---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sablier
  namespace: extras
  labels:
    app.kubernetes.io/name: sablier
data:
  # Ref: https://sablierapp.dev/#/configuration
  SABLIER_PROVIDER_NAME: kubernetes
  SABLIER_SESSIONS_DEFAULT_DURATION: 5m
  SABLIER_SESSIONS_EXPIRATION_INTERVA: 20s
  SABLIER_LOGGING_LEVEL: debug
  SABLIER_STRATEGY_DYNAMIC_SHOW_DETAILS_BY_DEFAULT: "true"
  SABLIER_STRATEGY_DYNAMIC_DEFAULT_THEME: hacker-terminal
  SABLIER_STRATEGY_DYNAMIC_DEFAULT_REFRESH_FREQUENCY: 5s
  SABLIER_STRATEGY_BLOCKING_DEFAULT_TIMEOUT: 1m
