apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: extras
resources:
  - config-map.yaml
helmCharts:
  - name: sablier
    namespace: extras
    releaseName: sablier
    version: 1.0.3
    repo: https://sablierapp.github.io/helm-charts
    valuesInline:
      readinessProbe:
        initialDelaySeconds: 5
        periodSeconds: 15
      livenessProbe:
        initialDelaySeconds: 5
        periodSeconds: 15
      resources: {}
