---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: bookmarks.brhd.io
  namespace: privacy
spec:
  endpoints:
    - dnsName: bookmarks.brhd.io
      recordTTL: 86400
      recordType: CNAME
      targets:
        - casa.brhd.io
