---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: karakeep
  namespace: privacy
spec:
  encryptedData:
    OAUTH_CLIENT_ID: AgDKqlhDuXhyniNhOh/xWVjASNbFszo5+4DAdmq+1SpKvp7EgLrIaf1J33BtuRtWw2IEq+RcFt8n95RE6VG4aiEGFFGjKcMSz/ATY1HVwhzaSAQty9EuXCEyiXTds2wc/SALYi+KlWpyzNC71EB+7fV2sqdlu2TKPVPYXYNMlwtIiS4lnfhcXyVBvDtzONG4hjTMeDniN6z6NZVw18LJimo6aw+vlilmtG9unyGMgoK+db05iGBqq6FnKSNfNxZBluAmoQfOPu5/WM6vYrD/F85vTWV7mzScyN3Y/MHsEAqLC3LvMP0OkfdeE2MbVWqphM7yx3B9gsBIoZhSc7gSCIQlb9l0SRnbJRIKQnlhTODuikMHg1hBNywlqeFcOL0lIZvCgsDgHQpfsEbNZ7rz9igmrP3tS2XHQ9ThC7bUXD+fBAwlRKoZ7LbXNNiHspjd9E/ePnfYmf4FvPObkgaJ+115+IZ8kkJiaAizJOI5zA8JeL2ggqIqgrGsnD23rLtCJwFWj+Bl+yEIU3LJ2q+SmAYAkPzuFpijkddvzlMUPhSwv4h/inLGHzya6hBlCI44U15nW33p54VPGfpKtPGEM8SabA8UYhvpyO7aUGE630HRpTGyTpoipCPAb5OOEEQC+u6uvJIE3Ukb/dGsO/wq+htmjlFhNyE3mYYa2IrRswtjhSikWcLq4UQaK1OG4HRyLJSSFpaaH6+74B03k5P+VdT2Iuvwjll+qRfwr+g79dypPL9w33f2z+CP
    OAUTH_CLIENT_SECRET: AgC3gJbzRKJbqaFnkF0IflKG/w1vzh9NgF1+GD0FjYfB4iyEgHvwEl4fLyMJctMaGTxc6r3Y5+z2p/+gaVsqp8izPQNsO9Zym0UYui8epb9eln89mYnKQix/at7DmMK16osGWD94/Z8Xu1MWsdlCqxoPaqw3tEe17uc62YNa9vxXEfwMApkyQnYEwNgjsMZR7DWX2I9nMtrldkxuxuDNviPkevmgPDc8J/mbOkx5U4Imwzl8aaYgn0eiSuAANHQOZe4FmWH2MzvdHB3pVeDnN0IsYyb/9QE9cSdkQozf/YNpKzvc793HdxiOGIYDwdYHUJz82dLXBOKgKR/V40K4EkqFbb2iGiLAiiW9cfhEfPiPrQzMA6VM/PKu/dwYOMJRZQ32gzyxQAKNlH5LQief/jdCMwexmrM6QDoHg8OvjelpqNFFdyD/Gk7tbUzPqn+Ym2dtCgcbJt/B41EKcpnhVoUyTTkn9LxFsB2K2hSZqMvmMoS/qAy754uQsFE0bcjozXV+vuNyX0krtpDhR8H7tpRVGMj8S1d1Ly7+/KsNNk5qdLsk2yOcvHg3OLWnGOXEb/Bm50//lzowxT6rTfirz4FYaBNE0oWaiKrFejfct2k1FyZtUcNM9Q9PcMjps2euAGiIRrHTneTVX8g35gCfOE4kIC/MyWFr15UFmXVcp5IlwWW7vm5uPfRD4NWaxsglW9SeTJ4ygYbAjsloVec15ub89k9j9sM7qK6EOEdQuIeFNoqLqb8m932RC3ZBVyjMCEkEJdAMmVrEIhYrW0BrFcZDCzxVdb9a+6dV3fPshCVFbm5RYwj33heQIFZM3HaugdjD6llF4X89LRTA323jQZtS0l+W/wftUpWOwlfTkOt+Vg==
  template:
    metadata:
      creationTimestamp: null
      name: karakeep
      namespace: privacy
    type: Opaque
