---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: karakeep-oauth
  namespace: privacy
spec:
  encryptedData:
    OAUTH_CLIENT_ID: AgDTOjQyKF4odzf0S0xqWDJOq38uCmYbPr1ZMqlgJ/1VkJGQx+zF1WiYB6dH0DXYK4M0C/WI3szeS5CJDylNJPgwQs8/PnCTaa9o6Hx8SlkRxPrq3g96Ry9ychJPyQGNBls/M/yS6/lksrMETZNlIJBtOlNCsEo6yyQ8FMpglQbsF9Lq0kc/HRIPn9Tsk2nXoIPAwB1pkrJfM3RBKKyCL2KD/sbxtG//LIk7N+zVoS77o1RrxwJ7a9u340TuM1UYX9hMnGYxbcqxgOMPmy/1w35x9EigrYLPQ4nvsezBHnQr+rEX3P6lpK02wRHPtquX+6DD+vnK8gSKEK2p0FUo3bxSAZ+83fMiVFfg8IfI+bblrZ+E+7jOi8hTTddcedJzdjz0Wc0hZYSsIgCbhZkuzoNrrTfRS5Cqz3TtWyCEjWcIsNq2RkSXw6pLt6NgTIBXyvB6jMHHRlQ5UwTUjiGOvMGQxZqePr3cN8aenmqwr5lbPYTsJAPMBlpDvUlCtpfbtxQ/BBWexXnpGw8kkFP3aiMy2C4ZFwnHH12Tf/rdpwAQbukX73+TkUEzN+LaTAlhQaag6aWwF6F+KALA5L2CqHO2MgXFtZvXyKhfT9WUg47UZtpS2QBiDVLTJmYJ38BhL+4l0/QqHOpfWkI6HlMEiOIRG7dBPA+FVSmr1GLiRMRsp+l3VQnj+vNuH/RLRo0VHSMZ68DrZvIljnHrnvJvj6qPbEJovXMllu64qYvnrKVtTcT1dnVAmKVJ
    OAUTH_CLIENT_SECRET: AgBlVyZhimJpLnlpxDqeMNjXpjxQ9LDIATOUSnKhEuRFa5EQejqxov2TFjkZonB/NuHbS3klVh+bo1cw6J3VkPY9Cfm+WiXGzChDsyPfTaq8NbpPbHJ5ydJsbdCnxHduCriPzUNVJNcWV7BRHbgB6azT9GFN4T+em/Zvmr0K4TuNoMDzHh0y5Cb2kpmOFP4YvwlEpEN7xLQ/RI761lbAzUwlvtykjVN9jA9cnkmj67nbSxw2IDlu824MXDPy/mXnekoBIrqR5KpaPG7M8l+9Ar6rTS+TxIyauvlfwSwV4IKuT/rVqfkIc6hEx999DXQgaDzmI0rHRQfPWB6fwCBP9yKScmv0giN19ywxXUBxHRcLbvp5yZheEh1rsBPP6mzC6QFfCN+DGbbrbDsLqlFGLX/cT+gigWeWirz30bJStsLrpkg1PQuPTJggXo/JNDRzZN+GSDTfJYX0oTK9rED140ny3IFgMj87LKccjWvZMvskl6pGcEsHqqyKdfN3AO6GzM534wL6cG1QZN1Mt29qinPJqhZvzqgrASfBxbb688JcBBaYCZsD2+ZV8I0WD+/eOQkeRGBfZ8KoPNO4zTISKpS7wNyojWhU1pTNPXLFEYQl57Eq/D3FeXMRRMGVL8IeQihkZJT1irMMWuSG0I3B0nQ59fO3AiW3C8xyhEGOdQ2b1kjoQ91unLV6zt/ILnGkAfRnZtczbPDb/J0AFQpR1YGrXb17PfRyyC1FNoELXxxBD6VjJEIRWN+ow+9+xrU5YMKIYdTv24uXXwD/HhqIn4sb4qvRVI3vskUhgQVPvEafsYRI0OCTy3/jAPB6BfcflBQaH/aSsptRBs33+By7vYBdA2klIdnvo2ypIEQeHSwk1A==
  template:
    metadata:
      creationTimestamp: null
      name: karakeep-oauth
      namespace: privacy
    type: Opaque
