{
 "title": "Intel GPU Metrics",
 "description": "Intel GPU Metrics based on the prometheus metrics from https://github.com/onedr0p/intel-gpu-exporter",
 "tags": [
  "per-node",
  "x86",
  "intel",
  "gpu"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"intel-gpu\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Actual Frequency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(igpu_frequency_actual{instance=~\"$instance\",job=\"intel-gpu\"})",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Render/3D Busy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(igpu_engines_render_3d_0_busy{instance=~\"$instance\",job=\"intel-gpu\"})",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Blitter Busy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(igpu_engines_blitter_0_busy{instance=~\"$instance\",job=\"intel-gpu\"})",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Frequencies",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(igpu_frequency_actual{instance=~\"$instance\",job=\"intel-gpu\"})",
     "legendFormat": "Actual"
    },
    {
     "expr": "avg(igpu_frequency_requested{instance=~\"$instance\",job=\"intel-gpu\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "GPU Requested Frequency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(igpu_frequency_requested{instance=~\"$instance\",job=\"intel-gpu\"})",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Video Busy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(igpu_engines_video_0_busy{instance=~\"$instance\",job=\"intel-gpu\"})",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "VideoEnchance Busy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(igpu_engines_video_enhance_0_busy{instance=~\"$instance\",job=\"intel-gpu\"})",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Busy Engines",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(igpu_engines_render_3d_0_busy{instance=~\"$instance\",job=\"intel-gpu\"})",
     "legendFormat": "Render/3D"
    },
    {
     "expr": "avg(igpu_engines_blitter_0_busy{instance=~\"$instance\",job=\"intel-gpu\"})",
     "legendFormat": "Blitter"
    },
    {
     "expr": "avg(igpu_engines_video_0_busy{instance=~\"$instance\",job=\"intel-gpu\"})",
     "legendFormat": "Video"
    },
    {
     "expr": "avg(igpu_engines_video_enhance_0_busy{instance=~\"$instance\",job=\"intel-gpu\"})",
     "legendFormat": "Video Enchance"
    }
   ]
  },
  {
   "title": "GPU Frequencies",
   "type": "timeseries",
   "description": "Current frequency of graphics (shader) clock.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "igpu_frequency_actual{instance=~\"$instance\",job=\"intel-gpu\"}",
     "legendFormat": "actual"
    },
    {
     "expr": "igpu_frequency_requested{instance=~\"$instance\",job=\"intel-gpu\"}",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Busy Engines",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_render_3d_0_busy{instance=~\"$instance\",job=\"intel-gpu\"}",
     "legendFormat": "Render/3D"
    },
    {
     "expr": "igpu_engines_blitter_0_busy{instance=~\"$instance\",job=\"intel-gpu\"}",
     "legendFormat": "Blitter"
    },
    {
     "expr": "igpu_engines_video_0_busy{instance=~\"$instance\",job=\"intel-gpu\"}",
     "legendFormat": "Video"
    },
    {
     "expr": "igpu_engines_video_enhance_0_busy{instance=~\"$instance\",job=\"intel-gpu\"}",
     "legendFormat": "Video Enchance"
    }
   ]
  }
 ]
}