---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: snapotter
  namespace: extras
spec:
  encryptedData:
    DATABASE_URL: AgDLicFdvxzwhY49Xq9TBQbAJfTMbtUw7YR9ioN3tXmisg1/cWPePi6pKJ+3fVAip0b7OaUBhCRIpYiWDPMulql8yD01EcRauXvQuTpLvLccaKmWfsrKOx/DYh0YR8+VRYwnGGV5fFbSHjE92lJ5MkMQirZEZxh3+6tqtJEOiFQNxr1nfbJ1HcrIbQM1/agi+o5YQmnzDpFnl7bGeSz+RRrITLUPh7jT737Xwo4M8HURpqIWnkI3nMU+tfvlr29tBz4wz2nv0ANxO/Ze1tpAmm8pCxmHHFrKMiI1L85M6ubGWjA8BzPF8uAxWd6LUKPSgmYwFw+qWFQJBWVaozeNsdrFFYpNuDEcMKCCDPJFgw/0SPqjeo/P5Xp1lLOzRqBor7jVaM6E2aOmlkE2CoX46qfxuu2GJ/0+WbD6Ig8FnnCpcXi3M1o/NOrPfo2+A27rk2rSOcTrJ6OlZNH3vjmtRPp7N1iA9wDt6Mgpb4uhfa/7NA76TE6mRj3RPJZuMru78l6A5ZcJcv9sEyrDqGuis8Ti5+aM1Iv3VJ214tZCXXJvf47DXNAy/3uduZrIXrwU2w2Zzk476RsglETg7k34hEbhnr/3XrdN4B9mngeycz3gkDHasShMpk0gNhvfi1NHkcU/imnOrS9WZMoWaoSs56XjQmtjzM2VC27+TjXtb2NlxapkWFB39++9DdPFz9meoJxdZDuCs+G8A4wDiEU2nVU02bGT8UwUtY7IIJ+rDxAAb0AgwQSzQfBsAtfFyveOTcIc71oN5in5w7uWHFn4hUkFpo/8B049KNiobZ/BVR7aRWib4HPFWYIg7oRuoyff8i+ToTVYb4utvaLSMQ==
    DEFAULT_PASSWORD: AgBHmRauiBu9kRTqiXQ3BzbSfUplaQtOvQ9fEMqqp76NUbsI+akmRPncI9lO+4l3TJkc0armnsbBYuSuwPp74hZXmwzBYjCdXzPQHGPX3xUeTwray3bIhrBy5zqsc4kFLwy9z+dv9p1w35virMy1zSHLcTI2ln40w50BqR+5s/XTDO+6wnguJH2nvGxT9yIe5zxQpF8LPwO+rejw+oMKOe5HvJTvFAxURno7LHSYIcF16o1BbL7JAIqWfMRGOTuHXtI20xx8FLi9sbSBQsEhaHwcTUkEO/KQQj5xGtgicmDuWOjWiupGkTBk9K5x1nwVAJnPqUutATYEutW0xWcmgLusazjWpMCKgHWRhLGiTIyLQVSXt06hkGVIqRDtJ2Kpqt/KvAJQkZ0iyFSaU6z9LNGWwog8X8cDXAMAHbJE4uSBiSmYJf5D7rg285qpy4qagkb7vjxQz4ONlOCC6wxiKk31vqKfewjstCY1w8HRXOwtvzrQZFyaoihKlZabUP9QRoOyF1yNf2roU0Mc56HGOUEMrs64aSDfzCCQEJQGdKdClxsscVmuoPLE6eMzC8G+/yYRuv2aSqcmrtjkNcEeScBkt6iGivicKU5sNXPiqwxLELZHbOky/avy2/NfDFh49nDBVconpGTohg5JFl5ALjYuGdvmdQvgKCB/xp2qBptbgGG8aH+25Hu4PJ0ABiIuU7zDSgfGYsKw6cfY1FBDE1QpFRT4ukvbEDe9+WXf
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: snapotter
      name: snapotter
      namespace: extras
    type: Opaque
