{
 "title": "Media Dashboard",
 "tags": [
  "sonarr",
  "readarr",
  "radarr",
  "lidarr",
  "prowlarr",
  "sabnzbd",
  "music",
  "movies",
  "tv",
  "media"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "prowlarr_instance",
    "label": "Prowlarr Instance",
    "query": {
     "query": "label_values({__name__=~\"prowlarr_.*\"},instance)"
    }
   },
   {
    "name": "radarr_instance",
    "label": "Radarr Instance",
    "query": {
     "query": "label_values({__name__=~\"radarr_.*\"},instance)"
    }
   },
   {
    "name": "sonarr_instance",
    "label": "Sonarr Instance",
    "query": {
     "query": "label_values({__name__=~\"sonarr_.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Prowlarr - ${prowlarr_instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_system_status{instance=~\"${prowlarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"prowlarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prowlarr_system_health_issues{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Health Issues"
    },
    {
     "expr": "max(prowlarr_indexer_enabled_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Enabled Indexers"
    },
    {
     "expr": "max(prowlarr_indexer_total{instance=~\"${prowlarr_instance}\"} - prowlarr_indexer_enabled_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Disabled Indexers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Grabs"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Query Failures"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(prowlarr_indexer_average_response_time_ms{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Response Time"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) / sum(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Failed Queries"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "prowlarr_system_health_issues{instance=~\"${prowlarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexer Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(prowlarr_indexer_average_response_time_ms{instance=~\"${prowlarr_instance}\"}) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Agent Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(increase(prowlarr_user_agent_queries_total{instance=~\"${prowlarr_instance}\"}[$__rate_interval])) by (user_agent)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Queries by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (indexer)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (user_agent)\n",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Grabs by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (user_agent)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Radarr - ${radarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_system_status{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"radarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movie_downloaded_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "radarr_movie_monitored_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "radarr_movie_wanted_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Wanted"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_queue_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "radarr_movie_downloaded_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "radarr_history_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "History"
    },
    {
     "expr": "radarr_movie_filesize_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Disk Used"
    },
    {
     "expr": "radarr_rootfolder_freespace_bytes{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Disk Free"
    }
   ]
  },
  {
   "title": "Qualities",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movie_quality_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"radarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"radarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "radarr_movie_filesize_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 38 },
   "targets": [
    {
     "expr": "radarr_system_health_issues{instance=~\"${radarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sonarr - ${sonarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_system_status{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"sonarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_queue_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "sonarr_history_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "History"
    },
    {
     "expr": "sonarr_episode_downloaded_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Downloaded"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_series_monitored_total{instance=~\"${sonarr_instance}\"})",
     "legendFormat": "Series Monitored"
    },
    {
     "expr": "max(sonarr_series_total{instance=~\"${sonarr_instance}\"})",
     "legendFormat": "Series Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_season_monitored_total{instance=~\"${sonarr_instance}\"})",
     "legendFormat": "Seasons Monitored"
    },
    {
     "expr": "max(sonarr_season_total{instance=~\"${sonarr_instance}\"})",
     "legendFormat": "Seasons Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_episode_missing_total{instance=~\"${sonarr_instance}\"})",
     "legendFormat": "Episodes Missing"
    },
    {
     "expr": "max(sonarr_episode_total{instance=~\"${sonarr_instance}\"})",
     "legendFormat": "Episodes Total"
    }
   ]
  },
  {
   "title": "Qualities",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_episode_quality_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"sonarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"sonarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sonarr_series_filesize_bytes{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 61 },
   "targets": [
    {
     "expr": "sonarr_system_health_issues{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}