apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolverr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    group: media
spec:
  destination:
    name: in-cluster
    namespace: media
  source:
    path: kubernetes/cluster/media/flaresolverr
    repoURL: 'https://github.com/maxim-mityutko/home-infra.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
