apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: x-media-shared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  destination:
    name: in-cluster
    namespace: media
  source:
    path: kubernetes/cluster/media/x-media-shared
    repoURL: 'https://github.com/maxim-mityutko/home-infra.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
