apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  source:
    path: kubernetes/argocd
    repoURL: 'https://github.com/maxim-mityutko/home-infra.git'
    targetRevision: main
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
