---
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: searxng-scaler
spec:
  hosts:
    - search.brhd.io
  scaleTargetRef:
    name: searxng
    kind: Deployment
    apiVersion: apps/v1
    service: searxng
    port: 8080
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800 # 30 minutes
  scalingMetric:
    concurrency:
      targetValue: 1
