app:
  image: ghcr.io/lissy93/domain-locker-helm/domain-locker:0.1.4
  port: 3000
  env:
    DL_ENV_TYPE: selfHosted
    DL_PG_HOST: cnpg-default-rw.default.svc.cluster.local.
    DL_PG_PORT: 5432
    TZ: Europe/Amsterdam
  secretEnv:
    DL_PG_USER:
      name: domain-locker
      key: dl_pg_user  
    DL_PG_PASSWORD:
      name: domain-locker
      key: dl_pg_password
    DL_PG_NAME:
      name: domain-locker
      key: dl_pg_name
  ingress:
    enabled: true
    # ingressClassName: "nginx"
    annotations: # nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
    - host: domain.brhd.io
      paths:
      - path: /
        service:
          name: domain-locker-app
          port: 80
    # tls:
    # - hosts:
    #   - domain-locker.localhost.com
    #   secretName: domain-locker.localhost.com-tls

postgres:
  enabled: false
updater:
  enabled: true