{
 "title": "Speedtest Tracker",
 "description": "A dashboard to display data exported by Speedtest Tracker",
 "tags": [
  "speedtest tracker",
  "speedtest",
  "Prometheus"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Quick Speed Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download Speed",
   "type": "stat",
   "description": "Download speed - measures how quickly you can pull data from a server on the internet to your device.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(speedtest_tracker_download_bits)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "stat",
   "description": "Upload speed - measures how quickly you send data from your device to the internet.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(speedtest_tracker_upload_bits)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "stat",
   "description": "Also called latency, ping is the reaction time of your connection - that is, how quickly your device gets a response after you've sent out a request.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(speedtest_tracker_ping_ms)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ping Jitter",
   "type": "stat",
   "description": "Also called Packet Delay Variation (PDV), jitter is a measure of the variability in ping over time.\nThis metric shows the average difference between consecutive latency measurements.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(speedtest_tracker_ping_jitter_ms)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "stat",
   "description": "Packet loss occurs when a packet of data being sent over the internet is not received or is incomplete. This is described in the percentage of packets lost compared to packets sent.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(speedtest_tracker_packet_loss_percent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest result",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(last_over_time(speedtest_tracker_download_bits[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basic Speed Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Speedtest Results",
   "type": "timeseries",
   "description": "Download speed - measures how quickly you can pull data from a server on the internet to your device.\n\nUpload speed - measures how quickly you send data from your device to the internet.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (__name__) ({__name__=~\"speedtest_tracker_(download|upload)_bits\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "description": "Also called latency, ping is the reaction time of your connection - that is, how quickly your device gets a response after you've sent out a request.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (__name__) ({__name__=~\"speedtest_tracker_ping_ms\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "description": "Also called Packet Delay Variation (PDV), jitter is a measure of the variability in ping over time.\nThis metric shows the average difference between consecutive latency measurements.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (__name__) ({__name__=~\"speedtest_tracker_(download|ping|upload)_jitter_ms\"})",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Download Latency",
   "type": "timeseries",
   "description": "Low - Minimum Latency (formerly, Latency) measures the best case latency for the user at the time they decide to take a Speedtest.\n\nAvg - Primary-Server Latency is the interquartile mean (IQM or midmean) of the idle latency tests taken prior to the download portion of a Speedtest.\n\nHigh - Multi-server latency measures latency to multiple connections and then takes an average.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (__name__) ({__name__=~\"speedtest_tracker_download_latency_(high|low|iqm)_ms\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Latency",
   "type": "timeseries",
   "description": "Low - Minimum Latency (formerly, Latency) measures the best case latency for the user at the time they decide to take a Speedtest.\n\nAvg - Primary-Server Latency is the interquartile mean (IQM or midmean) of the idle latency tests taken prior to the download portion of a Speedtest.\n\nHigh - Multi-server latency measures latency to multiple connections and then takes an average.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (__name__) ({__name__=~\"speedtest_tracker_upload_latency_(high|low|iqm)_ms\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Advanced Speed Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Avg. Speed by Server",
   "type": "table",
   "description": "Average speeds received by server",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "{__name__=~\"speedtest_tracker_(download_bits|upload_bits|download_jitter_ms|upload_jitter_ms|ping_ms|ping_jitter_ms|packet_loss_percent|download_latency_iqm_ms|upload_latency_iqm_ms)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Tests",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=~\"speedtest_tracker_(download_bits|upload_bits|download_jitter_ms|upload_jitter_ms|ping_ms|ping_jitter_ms|packet_loss_percent|download_latency_iqm_ms|upload_latency_iqm_ms)\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}