apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: victoria-metrics-grafana
spec:
  rules:
    - host: grafana.brhd.io
      http:
        paths:
          - backend:
              service:
                name: keda-http-interceptor
                port:
                  number: 8080
