{
 "title": "Hardware Monitor",
 "tags": [
  "cpu",
  "temperature"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "Datasource", "query": "prometheus" },
   {
    "name": "INSTANCE",
    "label": "Instance",
    "query": {
     "query": "label_values(node_cpu_scaling_frequency_hertz,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "${INSTANCE}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "INSTANCE" },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by(chip) (node_hwmon_temp_celsius{instance=\"${INSTANCE:raw}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Frequency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_cpu_scaling_frequency_hertz{instance=\"${INSTANCE:raw}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Immediate Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=\"${INSTANCE:raw}\"}",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  }
 ]
}