apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: cnpg-ha-rw-pooler
  namespace: default
spec:
  cluster:
    name: cnpg-ha
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "200"
      default_pool_size: "10"
      reserve_pool_size: "5"
      reserve_pool_timeout: "5"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cnpg-ha-rw-pooler
    spec:
      containers:
        - name: pgbouncer
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: cnpg-ha-rw-pooler
                topologyKey: kubernetes.io/hostname
