apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cnpg-ha-rw-pooler
  namespace: default
  labels:
    app.kubernetes.io/name: cnpg-ha-rw-pooler
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cnpg-ha-rw-pooler
