---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: mcp.vl.brhd.io
  namespace: ai
spec:
  endpoints:
    - dnsName: mcp.vl.brhd.io
      recordTTL: 86400
      recordType: CNAME
      targets:
        - casa.brhd.io
