---
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: it-tools-scaler
spec:
  hosts:
    - it-tools.brhd.io
  scaleTargetRef:
    name: it-tools
    kind: Deployment
    apiVersion: apps/v1
    service: it-tools
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800 # 30 minutes
  scalingMetric:
    concurrency:
      targetValue: 1
