---
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: it-tools-scaler
spec:
  target:
    service: it-tools
    port: 80
  rules:
    - hosts:
        - it-tools.brhd.io
  scalingMetric:
    concurrency:
      targetValue: 50
  # timeouts:
  #   readiness: 30s
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: it-tools-scaler
spec:
  scaleTargetRef:
    name: it-tools
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 60
  initialCooldownPeriod: 600
  cooldownPeriod: 1800
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: it-tools-scaler
